name: "coverage"
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: ArtiomTr/jest-coverage-report-action@v2
