name: Coverage report
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      checks: write
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # threshold: 80  # optional parameter
